safe: true
markdown: redcarpet

# Permalinks
permalink:    pretty

# Server
source:       ./dist

# Site
title: Site Title

tagline: Tagline
  
# Author
author:
  name: Your Name
  email: your@email.com
  github : yourgithub
  twitter : yourtwitter

subscribe_rss: /atom.xml
