# Build
dest: _site

exclude: ["README.md", "Rakefile", "CHANGELOG.md"]

# Site metadata
title: Blog
description: >
  "Blog for Assemble."
tagline: Site Tagline
author :
  name : Name Lastname
  email : blah@email.test
  github : username
  twitter : username
  feedburner : feedname

# License info
license:
  type: MIT License
  url: ./license/index.html


# URLs
blog: http://hariadi.github.io/assemble-jekyll
repo: https://github.com/hariadi/assemble-jekyll
download:
  source: <%= site.repo %>/archive/master.zip
  source: <%= site.repo %>/archive/master.zip


# SEO/SEM
google_analytics: false
google_site_id: false


# Comments
disqus:
  shortname: assemble-jekyll


# Social
social:
  twitter:
    via: hariadi
    username: hariadi
  facebook: false
  gplus: false
  hn: false
  google: false


# Sharing
social:
  twitter: false
  facebook: false
  gplus: false
  hn: false
  google: false


