# Build
dest: _site


# Site metadata
title: Blog
lead: false
description: >
  "Blog for Assemble."

# License info
license:
  type: MIT License
  url: ./license/index.html


# URLs
blog: http://hariadi.github.io/assemble-jekyll
repo: https://github.com/hariadi/assemble-jekyll
download:
  source: <%= site.repo %>/archive/master.zip
  source: <%= site.repo %>/archive/master.zip


# SEO/SEM
google_analytics: false
google_site_id: false


# Comments
disqus:
  shortname: assemble-jekyll


# Social
social:
  twitter:
    via: hariadi
    username: hariadi
  facebook: false
  gplus: false
  hn: false
  google: false


# Sharing
social:
  twitter: false
  facebook: false
  gplus: false
  hn: false
  google: false


